### ISSUE TITLE
Issues getting RapidBlock running: disabled by default?

### ISSUE THREAD

**Issue by krusynth** [rapidblock-org/rapidblock#6]
Hi there, I'm a brand new user trying to get RapidBlock up and running on my Mastodon instance.

I've installed RapidBlock via apt, using the one-liner install script in the README, but I don't see any new instances blocked in my Admin panel.

Looking at [this line in the config](https://github.com/rapidblock-org/rapidblock/blob/fe37ea0f68b01c6050872ec59c97161df5d5a29c/dist/cron.default#L17) it appears that the tool is disabled by default, is that correct? Do I need to flip that bit to get this to run? I don't see any other installation instructions but perhaps I missed something?

Thanks for the great tool!

**Comment by krusynth** [comment]
Thanks for that. I have to admit, I'm not entirely sure what the `INSTANCES` variable does here - is there some documentation for all of this that I've somehow missed?

**Comment by chronos-tachyon** [comment]
It's the list of Mastodon instances that should be updated -- some people run more than one on the same machine, which works well for single-user instances.

The current version of RapidBlock directly writes to the database, so `INSTANCES` tells it how to access Mastodon's PostgreSQL database.

```
mastodon-4.x|postgresql:///mastodon?host=/run/postgresql&port=5433
```

The first part of an `INSTANCES` row is the version of Mastodon that you're using.  `mastodon-3.x` and `mastodon-4.x` are supported currently, although a future version will have two different ways of updating Mastodon 4.x (direct writes to the SQL database, or using the REST API) and this string will eventually let you pick which one to use.  I also eventually hope to support other ActivityPub software besides Mastodon, but I haven't gotten started on that work.

The second part is (for `mastodon-4.x`) a PostgreSQL database connect URL.  The `postgresql:` URL syntax is documented [in the PostgreSQL client documentation](https://www.postgresql.org/docs/current/libpq-connect.html#id-1.7.3.8.3.6).  For the default of `postgresql:///mastodon?host=/run/postgresql&port=5433`, it means "use the Postgres database named `mastodon` that's being served by the Postgres server running on the local machine, reachable via the Unix socket at `/run/postgresql/.s.PGSQL.5433`".

**Comment by krusynth** [comment]
I appreciate this! 

Again, is there any sort of official documentation to reference?  I'm not sure how a layperson (e.g., me) would get up and running with this without reading every line of code. I'm trying to muddle through here, but there are still some gaps. And I hate having to ask on Issues when I could RTFM and not bug you!

**Comment by chronos-tachyon** [comment]
I'm afraid I just haven't had time to write the documentation yet.  I'm very aware that it needs to be written, but I haven't had much time to devote to RapidBlock since the initial spurt of activity in November.

**Comment by krusynth** [comment]
Hi there, just bumping this issue.  I've tried tinkering with the settings but I *never* was able to get this to work. Is this project dead? The website is down too.

**Comment by chronos-tachyon** [comment]
Yeah, please see https://codeberg.org/oliphant/blocklists or other alternatives.  I just don't have the personal energy to keep up in this space.
